# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudDeploy < Formula
  desc "Manifest-driven multi-cloud deployment tool for AWS, GCP, Azure, and OCI"
  homepage "https://github.com/jvreagan/cloud-deploy"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jvreagan/cloud-deploy/releases/download/v1.1.0/cloud-deploy_Darwin_x86_64.tar.gz"
      sha256 "bdfda344f25c4259ddb05ed654ed639ddc6b17c872422d6a976151a49e59665a"

      def install
        bin.install "cloud-deploy"
        bin.install "manifest-ui"

        # Install web UI assets
        (prefix/"web").install Dir["web/*"]
      end
    end
    on_arm do
      url "https://github.com/jvreagan/cloud-deploy/releases/download/v1.1.0/cloud-deploy_Darwin_arm64.tar.gz"
      sha256 "c04131fa02a7e16889bf153cacde8fd24be4479255fab249be0b7a4527b0974c"

      def install
        bin.install "cloud-deploy"
        bin.install "manifest-ui"

        # Install web UI assets
        (prefix/"web").install Dir["web/*"]
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jvreagan/cloud-deploy/releases/download/v1.1.0/cloud-deploy_Linux_x86_64.tar.gz"
        sha256 "1c66ea6f926f1e880236dbae7ef0a0b11f581f8d49c811e84cf60e08c6d4d6d7"

        def install
          bin.install "cloud-deploy"
          bin.install "manifest-ui"

          # Install web UI assets
          (prefix/"web").install Dir["web/*"]
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jvreagan/cloud-deploy/releases/download/v1.1.0/cloud-deploy_Linux_arm64.tar.gz"
        sha256 "d207a96b2ec15816987d8d9f4db5715217926b964e771938f036a99cfc6b347a"

        def install
          bin.install "cloud-deploy"
          bin.install "manifest-ui"

          # Install web UI assets
          (prefix/"web").install Dir["web/*"]
        end
      end
    end
  end

  test do
    system "#{bin}/cloud-deploy", "-version"
    system "#{bin}/manifest-ui", "-h"
  end
end
