# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudDeploy < Formula
  desc "Manifest-driven multi-cloud deployment tool for AWS, GCP, Azure, and OCI"
  homepage "https://github.com/jvreagan/cloud-deploy"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jvreagan/cloud-deploy/releases/download/v0.5.0/cloud-deploy_Darwin_x86_64.tar.gz"
      sha256 "2a7264b0466b6f8fc2e6ff443930b6e8ad3b44ee075170543c344bce0d14323e"

      def install
        bin.install "cloud-deploy"
        bin.install "manifest-ui"

        # Install web UI assets
        (prefix/"web").install Dir["web/*"]
      end
    end
    on_arm do
      url "https://github.com/jvreagan/cloud-deploy/releases/download/v0.5.0/cloud-deploy_Darwin_arm64.tar.gz"
      sha256 "26d622fee29f279732b7229210d4d2055892ca6a1a8a5e8a081b89c76b8cb304"

      def install
        bin.install "cloud-deploy"
        bin.install "manifest-ui"

        # Install web UI assets
        (prefix/"web").install Dir["web/*"]
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jvreagan/cloud-deploy/releases/download/v0.5.0/cloud-deploy_Linux_x86_64.tar.gz"
        sha256 "22d4c2157f5595bb4f937cfbfd39046203b6bfe59d877edc83cf1ae599e46f04"

        def install
          bin.install "cloud-deploy"
          bin.install "manifest-ui"

          # Install web UI assets
          (prefix/"web").install Dir["web/*"]
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jvreagan/cloud-deploy/releases/download/v0.5.0/cloud-deploy_Linux_arm64.tar.gz"
        sha256 "74f7840532cd75692f3b9f712895bbf1e60b7e05c04d0ffcd3c4ccd5a8a6095a"

        def install
          bin.install "cloud-deploy"
          bin.install "manifest-ui"

          # Install web UI assets
          (prefix/"web").install Dir["web/*"]
        end
      end
    end
  end

  test do
    system "#{bin}/cloud-deploy", "-version"
    system "#{bin}/manifest-ui", "-h"
  end
end
